### ISSUE TITLE
IOError in train.py

### ISSUE THREAD

**Issue by SongKAY** [yunjey/show-attend-and-tell#26]
When I run train.py,i got the problem says
`Traceback (most recent call last):
  File "train.py", line 25, in <module>
    main()
  File "train.py", line 8, in main
    data = load_coco_data(data_path='./data', split='train')
  File "/home/sxm/bishe/tensorflow-git/show-attend-and-tell-tensorflow/core/utils.py", line 13, in load_coco_data
    data['features'] = hickle.load(os.path.join(data_path, '%s.features.hkl' %split))
  File "/home/sxm/Tensorflow/local/lib/python2.7/site-packages/hickle.py", line 616, in load
    h5f = file_opener(fileobj)
  File "/home/sxm/Tensorflow/local/lib/python2.7/site-packages/hickle.py", line 154, in file_opener
    h5f = h5.File(filename, mode)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 79, in make_fid
    fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
  File "h5f.pyx", line 71, in h5py.h5f.open (h5py/h5f.c:1806)
IOError: unable to open file (File accessibilty: Unable to open file)
`
Is there anybody has the same problem?I don't know how to fix it...

**Comment by Shaimaaf16** [comment]
i'm facing the same problem. anyone??
problem : 
IOError: Unable to open file (Unable to open file: name = './data/train/train.features.hkl', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by EMCL** [comment]
before training, RUN propro.py to prepare the features.It will saved to /data/train/train.features.hkl. Then you can call it. This is not an error.

**Comment by SongKAY** [comment]
Thank you

**Comment by rohitsaluja22** [comment]
thanks
