### ISSUE TITLE
What is the difference between this code and the original in details ? Help me please. 

### ISSUE THREAD

**Issue by MenSanYan** [yunjey/show-attend-and-tell#59]
I want to repeat the results same as the original paper. But, I get a BLEU-1 score about 0.66. What can I do next to achieve the same results? I have been frustrated for a long time. Please.

**Comment by JunHyungYu** [comment]
Did you run this yunjey's code without any errors? 
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    main()
  File "train.py", line 22, in main
    solver.train()
  File "/home/yujunhyung/show-attend-and-tell-tensorflow/core/solver.py", line 77, in train
    loss = self.model.build_model()
  File "/home/yujunhyung/show-attend-and-tell-tensorflow/core/model.py", line 168, in build_model
    _, (c, h) = lstm_cell(1, inputs=tf.concat(1, [x[:,t,:], context]), state=[c, h])

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
I get this error when I run train.py code.
Is there any solution?

i used tensorflow 0.11.0 version & python2.7

What version did you use?

**Comment by MenSanYan** [comment]
@JunHyungYu As far as I know, there exists some incompatibilities among different tensorflow versions. A good choice is to copy the  error information and paste it in Google for resolution. I ever encountered a revised version of this repository that is compatible with the most recent tensorflow. Another choice is to search that revised version in github, after that there should exist no errors. Good luck!
